config/routes.rb
Rails.application.routes.draw do

  get 'charges/new'

  get 'charges/create'

  mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'
  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks"
  }
  root to: 'dashboards#index'
  resources :books, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    collection do
      get "authors"
      get "author_books"
      get "verify_books"
      get "my_books"
    end
    member do
      get "approve_book"
    end
  end
  resources :categories, only: [:index] do
    collection do
      get 'category_books'
    end
  end
  resources :plans, only: [:index, :show]
  resources :charges, only: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  require 'carrierwave/orm/activerecord'
  belongs_to :author, foreign_key: "user_id", class_name: "User"
  belongs_to :category, required: true
  validates :name, :user_id, :category_id, :description, :book_pdf, :avatar, presence: :true
  mount_uploader :book_pdf, BookPdfUploader
  mount_uploader :avatar, AvatarUploader
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  load_and_authorize_resource
  skip_authorize_resource only: [:author_books, :authors]
  skip_before_filter :authenticate_user!, only: [:index, :authors, :author_books]

  def index
    @q = Book.ransack(params[:q])
    @books = @q.result(distinct: true).includes(:author).page(params[:page]).per(8)
  end

  def new
    @book = Book.new
    authorize! :new, @book
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      # admin = User.find_by(role_id: 3)
      # BookStoreMailer.new_book(@book, admin).deliver
      flash[:success] = "Book Successfully Created"
      redirect_to books_path
    else
      render "new"
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def authors
    @authors = User.where(role_id: 1)
  end

  def author_books
    @authors = User.select{|x| x.books.present?}
    if params[:user_id].present?
      @author = User.find(params[:user_id])
      @books = @author.books.page(params[:page]).per(8)
    else
      @author = @authors.first
      @books = @author.books.page(params[:page]).per(8)
    end
  end

  def open_book
    @book = Book.find(params[:id])
    redirect_to pdfjs.minimal_path(file: @book.book_pdf.url)
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:success] = "Book updated"
      redirect_to book_path(@book)
    else
      render "edit"
    end
  end

  def verify_books
    @books = Book.where(approved: false).order(:created_at)
  end

  def approve_book
    @book = Book.find(params[:id])
    @book.approved = true
    @book.save
    flash[:success] = "Book Successfully verified"
    redirect_to verify_books_books_path
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    flash[:danger] = "Book deleted"
    if current_user.admin?
      redirect_to verify_books_books_path
    else
      redirect_to books_path
    end
  end

  def my_books
    @books = current_user.books.page(params[:page]).per(8)
  end

  private

  def book_params
    params.require(:book).permit(:name, :book_pdf, :category_id, :description, :avatar).merge(user_id: current_user.id)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/author_books.html.erb
<div class="content-wrapper-form">
  <div class="heading-div">
    <div class="container">
      <h2>Authors</h2>
      <div class="pull-left page-flow ">
        <p> Home / <a href="/books/author_books">Author Books</a></p>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row" style="margin-top: 3em;
                  margin-bottom: 3em;">

      <div class="col-sm-3">
        <div class="cat">
          <ul class="nav nav-pills nav-stacked">
            <h3>AUTHORS</h3>
            <% @authors.each do |author| %>
              <li role="presentation" class="<%= 'active' if @author == author %>"><a href="<%=author_books_books_path(user_id: author.id)%>"><%= author.name%></a></li>
            <% end %>
          </ul>
        </div>
      </div>

      <div class="col-sm-9">
          <% if @books.present? %>
          <div class="row" style="margin-top: 1em;">
            <% @books.each do |book| %>
              <div class="col-sm-3">
                <div class="book-box">
                  <%= link_to book_path(book) do %>
                    <%= image_tag(book.avatar.url, class: "img-responsive" ) %>
                    <div class="book-tittle">
                      <h4><%= book.name %></h4>
                      <p><%= book.author.name%></p>
                    </div>
                  <% end %>
                </div>
              </div>
            <% end %>
          <% else %>


          <div class="no-result">
            <img src="/assets/no.png"/>
            <h2>NO RESULT FOUND</h2>
          </div>


          <% end %>
        </div>
      </div>
      <% if @books.present? %>
        <div align="center">
          <%= paginate @books %>
        </div>
      <% end %>

    </div>


  </div>

</div>

</div>

app/views/books/authors.html.erb
<div class="content-wrapper-form">
  <div class="heading-div">
    <div class="container">
      <h2>Authors</h2>
      <div class="pull-left page-flow ">
        <p> Home / <%= link_to "Authors", authors_books_path %> </p>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="clearfix"></div>
    <ul>
    <% @authors.each do |author| %>
      <li><%= link_to "#{author.name}", author_books_books_path(user_id: author.id) %></li>
    <% end %>
  </ul>
  </div>
</div>

app/views/books/edit.html.erb
<div class="content-wrapper-form">
  <div class="heading-div">
    <div class="container">
      <h2>Book form</h2>
    </div>
  </div>
  <div class="container">
    <div class="col-sm-6 col-sm-offset-3" style="margin-top:3em;">
      <%= form_for @book do |f| %>
      <% if @book.errors.any? %>
      <ul>
        <% @book.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
      <% end %>
        <div class="form-group">
          <label>Name</label>
          <%= f.text_field :name, class: "form-control", placeholder: "Name" %>
        </div>

        <div class="form-group">
          <label>Description</label>
          <%= f.text_area :description, class: "form-control", rows: "4", placeholder: "Description" %>
        </div>

        <div class="form-group">
          <label>Category</label>
          <%= f.collection_select :category_id, Category.all, :id, :name, {prompt: "Select Category"}, { class: "form-control"} %>
        </div>

        <div class="form-group">
          <label>Book cover image</label>
          <div class="input-group image-preview">
            <input type="text" style="  " class="form-control image-preview-filename" disabled="disabled">
            <span class="input-group-btn">
              <!-- image-preview-clear button -->
              <button type="button" class="btn btn-default image-preview-clear" style="display:none; padding-top: 9px;
              padding-bottom: 9px;">
              <span class="glyphicon glyphicon-remove"></span> Clear
              </button>
            <!-- image-preview-input -->
              <div class="btn btn-default image-preview-input" style="padding-top: 9px;
                padding-bottom: 9px;
                border-radius: 0px;">
                <span class="glyphicon glyphicon-folder-open"></span>
                <span class="image-preview-input-title">Browse</span>
                <input type="file" accept="image/png, image/jpeg, image/gif" validate="true" name="book[avatar]" value="#{@book.avatar.url}"/> <!-- rename it -->
              </div>
            </span>
          </div>
        </div>

        <div class="form-group file-book">
          <%# if f.object.book_pdf %>
            <p><%#= @book.book_pdf.file.filename %></p>
          <%# end %>
          <label>Book File</label>
          <%= f.file_field :book_pdf, class: "form-control", placeholder: "Book Pdf" %>
        </div>

        <div align="center" style="margin-bottom:1em;">
          <button class="btn btn-default"> SUBMIT</button>
        </div>

      <% end %>

    </div>
  </div>
</div>


<script>
$(document).on('click', '#close-preview', function(){
  $('.image-preview').popover('hide');
  // Hover befor close the preview
  $('.image-preview').hover(
      function () {
         $('.image-preview').popover('show');
      },
       function () {
         $('.image-preview').popover('hide');
      }
  );
});

$(function() {
  // Create the close button
  var closebtn = $('<button/>', {
      type:"button",
      text: 'x',
      id: 'close-preview',
      style: 'font-size: initial;',
  });
  closebtn.attr("class","close pull-right");
  // Set the popover default content
  $('.image-preview').popover({
      trigger:'manual',
      html:true,
      title: "<strong>Preview</strong>"+$(closebtn)[0].outerHTML,
      content: "There's no image",
      placement:'bottom'
  });
  // Clear event
  $('.image-preview-clear').click(function(){
      $('.image-preview').attr("data-content","").popover('hide');
      $('.image-preview-filename').val("");
      $('.image-preview-clear').hide();
      $('.image-preview-input input:file').val("");
      $(".image-preview-input-title").text("Browse");
  });
  // Create the preview image
  $(".image-preview-input input:file").change(function (){
      var img = $('<img/>', {
          id: 'dynamic',
          width:250,
          height:200
      });
      var file = this.files[0];
      var reader = new FileReader();
      // Set preview image into the popover data-content
      reader.onload = function (e) {
          $(".image-preview-input-title").text("Change");
          $(".image-preview-clear").show();
          $(".image-preview-filename").val(file.name);
          img.attr('src', e.target.result);
          $(".image-preview").attr("data-content",$(img)[0].outerHTML).popover("show");
      }
      reader.readAsDataURL(file);
  });
});
</script>

app/views/books/index.html.erb
<div class="content-wrapper-form">
  <div class="heading-div">
    <div class="container">
      <h2>All Books</h2>
      <div class="pull-left page-flow ">
        <p> Home / <a href="/books">Books</a>/ </p>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row" style="margin-top: 3em;
                  margin-bottom: 3em;">

      <div class="">
          <% if @books.present? %>
          <div class="row" style="margin-top: 1em;">
            <% @books.each do |book| %>
              <div class="col-sm-3">
                <div class="book-box">
                  <%= link_to book_path(book) do %>
                    <%= image_tag(book.avatar.url, class: "img-responsive" ) %>
                    <div class="book-tittle">
                        <h4><%= truncate(book.name, length: 24) %></h4>
                        <p><%= book.author.name%></p>
                    </div>
                  <% end %>
                </div>
              </div>
            <% end %>
          <% else %>


          <div class="no-result">
            <img src="/assets/no.png"/>
            <h2>NO RESULT FOUND</h2>
          </div>


          <% end %>
        </div>
      </div>
      <div align="center">
        <%= paginate @books %>
      </div>
    </div>


  </div>

</div>

</div>

app/views/books/my_books.html.erb
<div class="content-wrapper-form">
  <div class="heading-div">
    <div class="container">
      <h2>My Books</h2>
      <div class="pull-left page-flow ">
        <p> Home / <a href="/books/my_books">My Books</a></p>
        <% if can? :create, Book %>
         <%= link_to "New Book", new_book_path, class: "btn btn-default"%>
        <% end %>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row" style="margin-top: 3em;
                  margin-bottom: 3em;">

      <div class="">
          <% if @books.present? %>
          <div class="row" style="margin-top: 1em;">
            <% @books.each do |book| %>
              <div class="col-sm-3">
                <div class="book-box">
                  <%= link_to book_path(book) do %>
                    <%= image_tag(book.avatar.url, class: "img-responsive" ) %>
                    <div class="book-tittle">
                        <h4><%= truncate(book.name, length: 24) %></h4>
                        <p><%= book.author.name%></p>
                    </div>
                  <% end %>
                </div>
              </div>
            <% end %>
          <% else %>


          <div class="no-result">
            <img src="/assets/no.png"/>
            <h2>NO RESULT FOUND</h2>
          </div>


          <% end %>
        </div>
      </div>
      <div align="center">
        <%= paginate @books %>
      </div>
    </div>


  </div>

</div>

</div>

app/views/books/new.html.erb
<div class="content-wrapper-form">
  <div class="heading-div">\
    <div class="container">
      <h2>Book form</h2>
    </div>
  </div>
  <div class="container">
    <div class="col-sm-6 col-sm-offset-3" style="margin-top:3em;">
      <%= form_for @book, html: {id: "demo_form1"} do |f| %>
      <% if @book.errors.any? %>
      <ul>
        <% @book.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
      <% end %>
        <div class="form-group">
          <label>Name</label>
          <%= f.text_field :name, class: "form-control", placeholder: "Name", required: true, :minlength=>"6", "data-msg-required": "Name is required" %>
        </div>

        <div class="form-group">
          <label>Description</label>
            <%= f.text_area :description, class: "form-control", rows: "4", placeholder: "Description", required: true, "data-msg-required": "Please add a short description" %>
        </div>

        <div class="form-group">
          <label>Category</label>
          <%= f.collection_select :category_id, Category.all, :id, :name, {prompt: "Select Category"}, { class: "form-control", required: true, "data-msg-required": "Please select category"} %>
        </div>

        <div class="form-group">
          <label>Book cover image</label>
          <div class="input-group image-preview">
            <input type="text" style="  " class="form-control image-preview-filename" disabled="disabled">
            <span class="input-group-btn">
              <!-- image-preview-clear button -->
              <button type="button" class="btn btn-default image-preview-clear" style="display:none; padding-top: 9px;
              padding-bottom: 9px;">
              <span class="glyphicon glyphicon-remove"></span> Clear
              </button>
            <!-- image-preview-input -->
              <div class="btn btn-default image-preview-input" style="padding-top: 9px;
                padding-bottom: 9px;
                border-radius: 0px;">
                <span class="glyphicon glyphicon-folder-open"></span>
                <span class="image-preview-input-title">Browse</span>
                <input type="file" extension="png|jpg|jpeg" accept="image/png, image/jpeg, image/gif" name="book[avatar]" required data-msg-accept="Please upload image file with jpeg/png format" data-msg-extension="Please upload image file with jpeg/png format" data-msg-required= "Image is required"/>
              </div>
            </span>
          </div>
          <label id="book[avatar]-error" class="error" for="book[avatar]" style="display: none;">This field is required.</label>
        </div>

        <div class="form-group file-book">
          <label>Book File</label>
          <div class="field_with_errors">
            <%= f.file_field :book_pdf, :accept => 'application/pdf',"extension": "pdf", class: "form-control", placeholder: "Book Pdf", required: true, "data-msg-accept": "Please upload PDF File", "data-msg-extension": "Please upload PDF file", "data-msg-required": "Book file is required" %>
          </div>
        </div>

        <div align="center" style="margin-bottom:1em;">
           <%= f.submit "Submit", class: "btn btn-default demo" %>
        </div>

      <% end %>

    </div>
  </div>
</div>

<script>
  $(document).ready(function(){
     $("#demo_form1").validate();
  });
</script>


<script>
$(document).on('click', '#close-preview', function(){
  $('.image-preview').popover('hide');
  // Hover befor close the preview
  $('.image-preview').hover(
      function () {
         $('.image-preview').popover('show');
      },
       function () {
         $('.image-preview').popover('hide');
      }
  );
});

$(function() {

  // $('#demo1').submit(function(e) {
  //   alert();
  //   e.preventDefault();
  //   alert();// this will stop the form from submitting
  //   if (1>2) {
  //     $(this).submit();
  //   }
  // });
  // Create the close button
  var closebtn = $('<button/>', {
      type:"button",
      text: 'x',
      id: 'close-preview',
      style: 'font-size: initial;',
  });
  closebtn.attr("class","close pull-right");
  // Set the popover default content
  $('.image-preview').popover({
      trigger:'manual',
      html:true,
      title: "<strong>Preview</strong>"+$(closebtn)[0].outerHTML,
      content: "There's no image",
      placement:'bottom'
  });
  // Clear event
  $('.image-preview-clear').click(function(){
      $('.image-preview').attr("data-content","").popover('hide');
      $('.image-preview-filename').val("");
      $('.image-preview-clear').hide();
      $('.image-preview-input input:file').val("");
      $(".image-preview-input-title").text("Browse");
  });
  // Create the preview image
  $(".image-preview-input input:file").change(function (){
      var img = $('<img/>', {
          id: 'dynamic',
          width:250,
          height:200
      });
      var file = this.files[0];
      var reader = new FileReader();
      // Set preview image into the popover data-content
      reader.onload = function (e) {
          $(".image-preview-input-title").text("Change");
          $(".image-preview-clear").show();
          $(".image-preview-filename").val(file.name);
          img.attr('src', e.target.result);
          $(".image-preview").attr("data-content",$(img)[0].outerHTML).popover("show");
      }
      reader.readAsDataURL(file);
  });
});
</script>

app/views/books/show.html.erb
<div class="content-wrapper-form">
  <div class="heading-div">
    <div class="container">
      <h2><%=@book.name %></h2>
      <div class="pull-left page-flow ">
        <p> Home / <%= link_to "Books", books_path %> / <span><%= link_to "#{@book.name.upcase}", book_path(@book) %></span> </p>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="clearfix"></div>
      <div class="row" style="margin-top: 3em;
                  margin-bottom: 3em;">
        <div class="col-sm-8">
          <div class="book-view-wrapper">
            <div class="row" >
              <div class="col-sm-5">
                <!-- <img class="img-responsive book-shadow" src="/assets/list2.png" width="100%" /> -->
                <%= image_tag(@book.avatar_url, class: "img-responsive book-shadow", width: '100%')%>
              </div>

              <div class="col-sm-7">
                <div class="book-details">
                  <h3><%= @book.name %></h3>
                  <p><b>Author : <%= @book.author.name %></b></p>
                  <p><%= @book.description %>
                    <div class="clearfix"></div>
                   <!-- <a href="#">View more </a></p> -->
                   <%# binding.pry %>
                    <% if (can? :update, @book) || (current_user.user_valid?) %>
                      <%= link_to pdfjs.minimal_path(file: @book.book_pdf.url), target: :_blank do %>
                        <button class=" btn btn-default"> <i class="fa fa-book" aria-hidden="true"></i>  READ NOW  </button>
                      <% end%>
                    <% else %>
                      <%= link_to plans_path do %>
                          <button class=" btn btn-default"> <i class="fa fa-book" aria-hidden="true"></i>  Please upgrade your plan to read this book!  </button>
                      <% end%>
                    <% end %>
                    <% if can? :update, @book %>
                      <%= link_to "Edit", edit_book_path(@book), class: "btn btn-default btn-edit" %>
                    <% end %>
                    <% if (can? :verify_books, @book) && !@book.approved %>
                      <%= link_to "Approve", approve_book_book_path(@book), class: "btn btn-default btn-edit" %>
                      <%= link_to "Reject", root_path, class: "btn btn-default btn-edit" %>
                    <% end %>
                 </div>
                 <div class="clearfix"></div>
              </div>

            </div>
          </div>
          <div class="table-wrapper col-sm-12">
            <table class="table table-bordered">
              <tbody>
                <tr>
                  <td><b>Book Title</b></td>
                  <td><%= @book.name %></td>

                </tr>
                <tr>
                  <td><b>Author</b></td>
                  <td><%= @book.author.name %></td>

                </tr>
                <tr>
                  <td><b>ISBN</b></td>
                  <td>00004506556057047080</td>

                </tr>

                <tr>
                  <td><b>Edition Language</b></td>
                  <td>English</td>
                </tr>
                <tr>
                  <td><b>Book Category</b></td>
                  <td><%= @book.category.name.titleize%></td>
                </tr>

                <tr>
                  <td><b>Date Published</b></td>
                  <td><%= @book.created_at.strftime('%v') %></td>
                </tr>

              </tbody>
            </table>
          </div>

        </div>

      <div class="col-sm-4">
    </div>
  </div>
</div>

</div>

app/views/books/verify_books.html.erb
<div class="content-wrapper-form">
  <div class="heading-div">
    <div class="container">
      <h2>Books Under Review</h2>
      <div class="pull-left page-flow ">
        <p> Home / <a href="/books/verify_books">Verify Books</a> </p>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="clearfix"></div>
    <h3>Unverified Books</h3>
    <div class="books">
      <div class="owl-carousel owl-theme">
        <% if @books.present? %>
          <% @books.each do |book| %>
            <div class="item">
              <div class="book-box">
                <%= link_to book_path(book) do %>
                  <%= image_tag(book.avatar.url) %>
                  <div class="book-tittle">
                    <h4><%= book.name %></h4>
                    <p><%= book.author.name.titleize%></p>
                  </div>
                <% end %>
              </div>
            </div>
          <% end %>
        <% else %>
          Not books for review
        <% end %>
      </div>
    </div>
  </div>
</div>