config/routes.rb
Rails.application.routes.draw do

  get 'charges/new'

  get 'charges/create'

  mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'
  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks"
  }
  root to: 'dashboards#index'
  resources :books, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    collection do
      get "authors"
      get "author_books"
      get "verify_books"
      get "my_books"
    end
    member do
      get "approve_book"
    end
  end
  resources :categories, only: [:index] do
    collection do
      get 'category_books'
    end
  end
  resources :plans, only: [:index, :show]
  resources :charges, only: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  skip_before_filter :authenticate_user!, only: [:index]

  def index
    @categories = Category.all
    if params[:id].present?
      @category = Category.find(params[:id])
      @books = @category.books.page(params[:page]).per(8)
    else
      @category = Category.first
      @books = @category.books.page(params[:page]).per(8)
    end
  end

  def category_books
    @category = Category.find(params[:id])
    @books = @category.books.where(approved: true)
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/category_books.html.erb
<div class="content-wrapper-form">
  <div class="container">
    <div class="pull-left page-flow ">
      <p> Home / <%= link_to "Categories", categories_path %> / <span><%= link_to "#{@category.name.titleize}", category_books_categories_path(id: @category.id) %></span> </p>
    </div>
    <div class="clearfix"></div>
    <h3>Books</h3>
    <div class="owl-carousel owl-theme">
      <% if @books.present? %>
        <% @books.each do |book| %>
          <div class="item">
            <div class="book-box">
              <%= link_to book_path(book) do %>
                <%= image_tag(book.avatar.url) %>
                <div class="book-tittle">
                  <h4><%= book.name %></h4>
                  <p><%= book.author.name %></p>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
      <% else %>
        Sorry, No books available
      <% end %>
    </div>
  </div>
</div>

app/views/categories/index.html.erb
<div class="content-wrapper-form">
  <div class="heading-div">
    <div class="container">
      <h2>Categories</h2>
      <div class="pull-left page-flow ">
        <p> Home / <a href="/categories">Categories</a></p>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row" style="margin-top: 3em;
                  margin-bottom: 3em;">

      <div class="col-sm-3">
        <div class="cat">
          <ul class="nav nav-pills nav-stacked">
            <h3>CATEGORIES</h3>
            <% @categories.each do |category| %>
              <li role="presentation" class="<%= 'active' if @category == category %>"><a href="<%=categories_path(id: category.id)%>"><%= category.name%></a></li>
            <% end %>
          </ul>
        </div>
      </div>

      <div class="col-sm-9">
          <% if @books.present? %>
          <div class="row" style="margin-top: 1em;">
            <% @books.each do |book| %>
              <div class="col-sm-3">
                <div class="book-box">
                  <%= link_to book_path(book) do %>
                    <%= image_tag(book.avatar.url, class: "img-responsive" ) %>
                    <div class="book-tittle">
                      <h4><%= book.name %></h4>
                      <p><%= book.author.name%></p>
                    </div>
                  <% end %>
                </div>
              </div>
            <% end %>
          <% else %>


          <div class="no-result">
            <img src="/assets/no.png"/>
            <h2>NO RESULT FOUND</h2>
          </div>


          <% end %>
        </div>
      </div>
      <% if @books.present? %>
        <div align="center">
          <%= paginate @books %>
        </div>
      <% end %>

    </div>


  </div>

</div>

</div>