config/routes.rb
Rails.application.routes.draw do

  get 'charges/new'

  get 'charges/create'

  mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'
  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks"
  }
  root to: 'dashboards#index'
  resources :books, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    collection do
      get "authors"
      get "author_books"
      get "verify_books"
      get "my_books"
    end
    member do
      get "approve_book"
    end
  end
  resources :categories, only: [:index] do
    collection do
      get 'category_books'
    end
  end
  resources :plans, only: [:index, :show]
  resources :charges, only: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/plan.rb
class Plan < ApplicationRecord
  has_many :users

  def trial?
    name == "Trial Plan"
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  skip_before_filter :authenticate_user!, only: [:index]
  def index
    @plans = Plan.all
  end

  def show
    @plan = Plan.find(params[:id])
  end

end

app/views/plans/index.html.erb
<div class="content-wrapper-form">
  <div class="heading-div">
    <div class="container">
      <h2>Price Plans</h2>
      <div class="pull-left page-flow ">
        <p> Home / <%= link_to "Plans", plans_path %> </p>
      </div>
    </div>
  </div>

<%= form_tag charges_path, id: "myForm" do %>
  <div class="container">


    <div class="row db-padding-btm db-attached">
      <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4" >
        <div class="db-wrapper">
          <div class="db-pricing-eleven db-bk-color-one">
            <div class="price">
              <sup>$</sup>Free
              <small>For 15 days</small>
            </div>
            <div class="type">
              Trial Plan
            </div>
            <ul>

              <li><i class="glyphicon glyphicon-print"></i>Unlimited Books </li>
              <li><i class="glyphicon glyphicon-time"></i>15 days </li>
              <li><i class="glyphicon glyphicon-trash"></i>Lead Required</li>
            </ul>
            <div class="pricing-footer">
             <% if user_signed_in? %>
               <div class="free">
                <span>Free</span>
               </div>
             <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
       <div class="db-wrapper">
        <div class="db-pricing-eleven db-bk-color-two popular">
          <div class="price">
            <sup>$</sup>10
            <small>per month</small>
          </div>
          <div class="type">
            Premium Plan
          </div>
          <ul>

            <li><i class="glyphicon glyphicon-print"></i>Unlimited Books </li>
            <li><i class="glyphicon glyphicon-time"></i>1 Month </li>
            <li><i class="glyphicon glyphicon-trash"></i>Lead Required</li>
          </ul>
          <div class="pricing-footer">
          <input type="hidden" id="stripeToken" name="stripeToken"/>
          <input type="hidden" id="plan-id" name="plan_id"/>
              <input type="hidden" id="stripeEmail" name="stripeEmail"/>
              <% if user_signed_in? %>
              <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                data-image= 'https://stripe.com/img/documentation/checkout/marketplace.png',
                data-description="A month's subscription"
                data-amount="1000"
                data-name="BookStore"
                data-label="Join"
                data-email="<%=current_user.email if user_signed_in?%>"
                data-locale="auto">
              </script>
              <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
     <div class="db-wrapper">
      <div class="db-pricing-eleven db-bk-color-three">
        <div class="price">
          <sup>$</sup>50
          <small>For 6 months</small>
        </div>
        <div class="type">
          ADVANCE PLAN
        </div>
        <ul>

          <li><i class="glyphicon glyphicon-print"></i>Unlimited Books </li>
          <li><i class="glyphicon glyphicon-time"></i>6 Months </li>
          <li><i class="glyphicon glyphicon-trash"></i>Lead Required</li>
        </ul>
        <div class="pricing-footer">

         <script src="https://checkout.stripe.com/checkout.js"></script>
         <% if user_signed_in? %>
          <button id="customButton"  class="stripe-button-el" style="visibility: visible;"><span style="display: block; min-height: 30px;">Join</span></button>
         <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>
</div>



</div>

</div>

<script>
var handler = StripeCheckout.configure({
  key: 'pk_test_F4wzEM5E1SEVweuNXFAWktaY',
  image: 'https://stripe.com/img/documentation/checkout/marketplace.png',
  locale: 'auto',
  token: function(token) {
   $("#stripeToken").val(token.id);
   $("#stripeEmail").val(token.email);
   $("#myForm").submit();
    // You can access the token ID with `token.id`.
    // Get the token ID to your server-side code for use.
  }
});

document.getElementById('customButton').addEventListener('click', function(e) {
  // Open Checkout with further options:
  handler.open({
    name: 'Book Store',
    description: '6 months subscription',
    amount: "5000",
    email: "<%=current_user.email if user_signed_in?%>"
  });
  e.preventDefault();
});

// Close Checkout on page navigation:
window.addEventListener('popstate', function() {
  handler.close();
});
</script>

app/views/plans/show.html.erb
<div class="content-wrapper-form">
  <div class="container">
    <div class="pull-left page-flow ">
      <p> Home / <%= link_to "Plans", plans_path %> / <span><%= link_to "#{@plan.name}", plan_path(@plan) %></span> </p>
    </div>
    <div class="clearfix"></div>
      <div class="row">
        <div class="col-sm-8">
          <div class="book-view-wrapper">
            <div class="row" >
              <div class="col-sm-5">
                <div class="book-details">
                  <h3><%= @plan.name %></h3>
                 </div>
                 <div class="clearfix"></div>
              </div>
              <% if !@plan.trial? %>
                <%= link_to "Purchase", root_path, class: "btn btn-primary" %>
              <% end %>
            </div>
          </div>
          <div class="table-wrapper col-sm-12">
            <table class="table table-bordered">
              <tbody>
                <tr>
                  <td><b>Plan</b></td>
                  <td><%= @plan.name %></td>

                </tr>
                <tr>
                  <td><b>Amount</b></td>
                  <% if @plan.trial? %>
                    <td>Free</td>
                  <% else %>
                    <td><%= @plan.amount %>$</td>
                  <% end %>

                </tr>
                <tr>
                  <td><b>Validity</b></td>
                  <td><%= @plan.limit%> days</td>
                </tr>

              </tbody>
            </table>
          </div>

        </div>

      <div class="col-sm-4">
    </div>
  </div>
</div>

</div>