config/routes.rb
Rails.application.routes.draw do

  get 'charges/new'

  get 'charges/create'

  mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'
  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks"
  }
  root to: 'dashboards#index'
  resources :books, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    collection do
      get "authors"
      get "author_books"
      get "verify_books"
      get "my_books"
    end
    member do
      get "approve_book"
    end
  end
  resources :categories, only: [:index] do
    collection do
      get 'category_books'
    end
  end
  resources :plans, only: [:index, :show]
  resources :charges, only: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_customers.html.erb
<div class="testimonials">
  <div class="container">
    <h2>OUR HAPPY CUSTOMERS</h2>
    <div class="row">
      <div class="col-md-12" data-wow-delay="0.2s">
        <div class="carousel slide" data-ride="carousel" id="quote-carousel">
          <!-- Bottom Carousel Indicators -->
          <ol class="carousel-indicators">
            <li data-target="#quote-carousel" data-slide-to="0" class="active"><img class="img-responsive " src="https://s3.amazonaws.com/uifaces/faces/twitter/brad_frost/128.jpg" alt="">
            </li>
            <li data-target="#quote-carousel" data-slide-to="1"><img class="img-responsive" src="https://s3.amazonaws.com/uifaces/faces/twitter/rssems/128.jpg" alt="">
            </li>
            <li data-target="#quote-carousel" data-slide-to="2"><img class="img-responsive" src="https://s3.amazonaws.com/uifaces/faces/twitter/adellecharles/128.jpg" alt="">
            </li>
          </ol>
          <!-- Carousel Slides / Quotes -->
          <div class="carousel-inner text-center">
            <!-- Quote 1 -->
            <div class="item active">
              <blockquote>
                <div class="row">
                  <div class="col-sm-8 col-sm-offset-2">
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. !</p>
                    <small>Someone famous</small>
                  </div>
                </div>
              </blockquote>
            </div>
            <!-- Quote 2 -->
            <div class="item">
              <blockquote>
                <div class="row">
                  <div class="col-sm-8 col-sm-offset-2">
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. </p>
                    <small>Someone famous</small>
                  </div>
                </div>
              </blockquote>
            </div>
            <!-- Quote 3 -->
            <div class="item">
              <blockquote>
                <div class="row">
                  <div class="col-sm-8 col-sm-offset-2">
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. .</p>
                    <small>Someone famous</small>
                  </div>
                </div>
              </blockquote>
            </div>
          </div>
          <!-- Carousel Buttons Next/Prev -->
          <a data-slide="prev" href="#quote-carousel" class="left carousel-control"><i class="fa fa-chevron-left"></i></a>
          <a data-slide="next" href="#quote-carousel" class="right carousel-control"><i class="fa fa-chevron-right"></i></a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="subscribe">
      <h4>GET SPECIAL OFFER IN YOUR INBOX  </h4>
      <div class="row">
        <div class="col-sm-offset-3 col-sm-6">
          <div class="row">
            <div class="col-sm-8 xs-p" style="    padding: 0px;">
              <input type="text" class="form-control" placeholder="Enter your email address" />
            </div>
            <div class="col-sm-4 xs-c" style="    padding-left: 10px;">
              <button class="btn btn-subscribe"> SUBSCRIBE </button>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-4">
        <div class="footer-1">
          <img src="/assets/footer-logo.png" class="img-responsive" />
          <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,</p>
          <a href="#">Learn More About us</a>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="footer-2">
          <h4> <img src="/assets/loc.png" /> OUR MAIN OFFICE</h4>
          <p>Techversant, First Floor Lulu Cyber Tower,<br>
            Infopark, Kakkanad Kochi, <br>
            Kochi, Kerala 682030
          </p>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="footer-3">
          <h4> <img src="/assets/share.png" /> OUR MAIN OFFICE</h4>
          <p><img src="/assets/twit.png" /> Twitter </p>
          <p><img src="/assets/fb.png" /> Facebook </p>
          <p><img src='/assets/g.png' /> Google plus </p>
        </div>
      </div>
    </div>
  </div>
  <div class="footer-bottom">
    <p>Copyright © 2016-2017 Techversant,</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div class="header-top">
  <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <div class="row">
      <div class="col-sm-3 col-xs-6">
        <%= link_to root_path do %>
          <div class="logo">
            <img src="/assets/logo.png" class="img-responsive" />
          </div>
        <% end %>
      </div>
      <div class="col-sm-6 hidden-xs ">
        <div class="search-box">
          <%= search_form_for @q do |f| %>
            <input type="text" name="q[name_cont]" class="form-control ss" placeholder="Search books..." />
          <% end %>
        </div>
      </div>
      <div class="col-sm-3">
        <% unless current_page?('/users/sign_in') || current_page?('/users/sign_up') %>
          <div class="login">
            <% if user_signed_in? %>
              <div class="dropdown">
                <button class="dropbtn user-btn"><%= current_user.name %>  <img src="/assets/user.png" class="img-circle img-user" width="40px" height="40px" /></button>
                <div class="dropdown-content">
                  <div class="angle-top"></div>
                  <a href="<%= edit_user_registration_path %>">My Profile</a>
                  <a href="<%=my_books_books_path%>">My Books</a>
                  <% if can? :verify_books, Book %>
                    <a href="<%= verify_books_books_path %>">Verify Books</a>
                  <% end %>
                  <%= link_to destroy_user_session_path, method: :delete do %>
                  <button class=" btn btn-default btn-logout"> <span class="glyphicon glyphicon-log-out"></span> Log out</button>
                  <% end %>
                </div>
              </div>
            <% else %>
                <%= link_to "Login or Register", new_user_session_path, class: "btn btn-login"  %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<nav class="navbar navbar-default" data-spy="affix" data-offset-top="197" >
  <div class="container">
    <div class="navbar-header">
      <div style=" margin:5px;" class="custom-search hidden-sm hidden-md hidden-lg" id="hello">
        <input type="text" class="form-control" placeholder="search...">
      </div>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <img class="affix-logo" src="/assets/logo.png">

    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-center">

        <li class=<%= current_page?(root_path) ? "active" : ""%> ><a href="<%= root_path%>">HOME </a></li>
        <!-- <li class=<%#= current_page?(categories_path) ? "active" : ""%> ><a href="<%= root_path%>">CATEGORIES</a></li> -->
        <li class=<%= current_page?(categories_path) ? "active" : ""%>><a href="<%= categories_path%>">CATEGORIES</a></li>
        <li class=<%= current_page?(author_books_books_path) ? "active" : ""%> ><a href="<%= author_books_books_path %>">AUTHORS</a></li>
        <li class=<%= current_page?(books_path) ? "active" : ""%>><a href="<%= books_path %>">BOOKS</a></li>
        <li class=<%= current_page?(plans_path) ? "active" : ""%>><a href="<%= plans_path %>">PLANS</a></li>
        <% if user_signed_in? %>
          <div class="pull-right affix-login">
            <div class="login" style="">
              <div class="dropdown">
                <button class="dropbtn user-btn"><%= current_user.name %> <img src="/assets/user.png" class="img-circle img-user" width="40px" height="40px"></button>
                <div class="dropdown-content">
                  <div class="angle-top"></div>
                    <a href="<%= edit_user_registration_path %>">My Profile</a>
                    <a href="<%=my_books_books_path%>">My Books</a>
                    <a rel="nofollow" data-method="delete" href="/users/sign_out">
                      <button class=" btn btn-default btn-logout"> <span class="glyphicon glyphicon-log-out"></span> Log out</button>
                    </a>
                  </div>
                </div>
              </div>
          </div>
        <% end %>


      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="no-js" lang="">
  <head>
    <title>BookStore</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Book store</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="apple-touch-icon" href="apple-touch-icon.png">
    <%= favicon_link_tag asset_path('favicon.ico'), :rel => 'icon', :type =>  'image/png' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <header>
      <%= render "layouts/header" %>
    </header>
    <!-- Swiper -->
    <%= yield %>

    <% if current_page?(root_path) %>
      <%= render "layouts/customers" %>
    <% end %>

    <%= render "layouts/footer" %>
    <script>
        window.jQuery || document.write('<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"><\/script>')
    </script>
    <!-- Initialize Swiper -->

    <%= javascript_include_tag 'build'%>
    <script>
        var swiper = new Swiper('.swiper-container', {
          speed: 600,
          parallax: true,
          pagination: {
            el: '.swiper-pagination',
            clickable: true,
          },
          navigation: {
            nextEl: '.swiper-button-next',
            prevEl: '.swiper-button-prev',
          },
        });
    </script>
    <script>
        $('.owl-carousel').owlCarousel({
          loop: true,
          margin: 10,
          responsiveClass: true,
          responsive: {
            0: {
              items: 1,
              nav: true
            },
            600: {
              items: 3,
              nav: false
            },
            1000: {
              items: 6,
              nav: true,
              loop: false
            }
          }
        })
    </script>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html class="no-js" lang="">
  <head>
    <title>Login|BookStore</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Book store</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="apple-touch-icon" href="apple-touch-icon.png">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
    <script>
        window.jQuery || document.write('<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"><\/script>')
    </script>
    <!-- Initialize Swiper -->

    <%= javascript_include_tag 'build'%>
    <script>
        var swiper = new Swiper('.swiper-container', {
          speed: 600,
          parallax: true,
          pagination: {
            el: '.swiper-pagination',
            clickable: true,
          },
          navigation: {
            nextEl: '.swiper-button-next',
            prevEl: '.swiper-button-prev',
          },
        });
    </script>
    <script>
        $('.owl-carousel').owlCarousel({
          loop: true,
          margin: 10,
          responsiveClass: true,
          responsive: {
            0: {
              items: 1,
              nav: true
            },
            600: {
              items: 3,
              nav: false
            },
            1000: {
              items: 6,
              nav: true,
              loop: false
            }
          }
        })
    </script>
  </body>
</html>